name: MatrixSpigotBridge
authors: [ Ilamparithi, David B ]
main: com.pseudosmp.msb.MatrixSpigotBridge
version: ${project.version}
description: ${project.description}
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
  msb:
    description: Main command for MatrixSpigotBridge
    usage: /msb [ping | reload | restart]
    aliases: [matrixspigotbridge, msb, matrix]