name: MatrixSpigotBridge
authors: [ Ilamparithi ]
main: com.pseudosmp.msb.MatrixSpigotBridge
version: ${project.version}
description: ${project.description}
api-version: 1.13
softdepend: [PlaceholderAPI]