# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.1
    - name: Set up JDK 11
      uses: actions/setup-java@v4.4.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn install -e
    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: MatrixSpigotBridge
        path: ./target/MatrixSpigotBridge.jar
